require 'nester'
require 'math'

-- Constant used to enable unit test functions
## WBTFOREST_UNITTEST = true
require 'wbtforest'

## if pragmas.nogc then -- the GC is disabled, must manually deallocate memory
##  static_error("Use the unit test webforest-nogc-test.nelua in nogc mode")
## end

-- Customize nester configuration.
nester.stop_on_fail = false

nester.describe('wbtforest', function()
  nester.before(function(name: string)
    -- This function is run before every test.
  end)

  nester.describe('wbtforest funs', function() -- Describe blocks can be nested.
    nester.it('instanciating default', function()
      local forest: wbtforest(integer, integer) <close>
      expect.equal(#forest, 0) -- creates doubly linked list
      expect.equal(#forest, 0) -- uses doubly linked list
    end)

    nester.it('instanciating general', function()
      local forest: wbtforest(integer, integer, nil, GeneralAllocator)
      forest:destroy()
    end)

    nester.it('insert & get', function()
      local forest: wbtforest(integer, integer)
      expect.equal(#forest, 0)
      local wbt1 <close> = forest:makewbtmap() -- : wbtmapT
      expect.equal(#forest, 1)
      local wbt2 <close> = forest:makewbtmap() -- : wbtmapT
      expect.equal(#forest, 2)
      local wbt3 <close> = wbt2:insert(42,-42)
      expect.equal(wbt3:get(42,-999), -42)
      expect.equal(wbt3:get(41,-999), -999)
      expect.equal(wbt2:get(42,-999), -999)
      forest:destroy()
    end)

    nester.it('API', function()
      local forest: wbtforest(integer, integer) <close>
      local wbt1 <close> = forest:makewbtmap() -- : wbtmapT
      local wbt2 <close> = forest:makewbtmap() -- : wbtmapT
      local wbt3 <close> = forest:makewbtmap() -- : wbtmapT
      wbt2 = wbt1:insert(0, 42)
      wbt2 = wbt1:delete(0)
      wbt2 = wbt1:delmax()
      wbt2 = wbt1:delmin()
      local w = wbt1:get(0, 1)
      local k,v = wbt1:getmax(-1, -2)
      k,v = wbt1:getmin(-1, -2)
      k,v = wbt1:getNth(9, -1, -2)
      k,v = wbt1:getnext(8, -1, -2)
      k,v = wbt1:getprev(7, -1, -2)
      w = wbt1:getrank(0, -1)
      --
      local b = wbt1:contains(6)
      wbt3 = wbt1:union(wbt2)
      wbt3 = wbt1:intersection(wbt2)
      wbt3 = wbt1:difference(wbt2)
      wbt3 = wbt1:symmetricdifference(wbt2)
      b = wbt1:issubset(wbt2)
      b = wbt1:ispropersubset(wbt2)
      b = wbt1:setequal(wbt2)
      b = wbt1:disjoint(wbt2)
      local function merge(k: integer, v1: integer, v2: integer)
        if k > 0 then return v1 + v2 else return v1 - v2 end
      end
      wbt3 = wbt1:unionmerge(wbt2, merge)
      wbt3 = wbt1:intersectionmerge(wbt2, merge)
    end)

    nester.it('grow manual', function()
      local forest: wbtforest(integer, integer, nil, GeneralAllocator) <close>
      --PRINTF!("About to make\n")
      local wbt1 = forest:makewbtmap() -- : *wbtmapT NG?
      --PRINTF!("About to loop\n")
      for i = 1, 240 do
        local wbt2 = wbt1:insert(i,-i) -- : *wbtmapT
        --wbt1 = wbt1:insert(i,-i)
        --PRINTF!("%d: %s\n", i, wbt1:treetostring())
        --PRINTF!("forest len %d i %d nodes %d marks %d\n", #forest, i, #forest.nodes, #forest.marks * 64)
        --PRINTF!("i %d wbt2 siz %d\n", i, #wbt2)
        wbt1, wbt2 = wbt2, wbt1
        expect.equal(#forest, 2)
        --wbt2:destroy()
        general_allocator:delete(wbt2) -- __delete metamethod calls wbt2:destroy()
        expect.equal(#forest, 1)
        --PRINTF!("i %d wbt1 siz %d\n", i, #wbt1)
        expect.equal(#wbt1, i)
      end
      expect.equal(wbt1:get(42,-999), -42)
      expect.equal(wbt1:get(222,-999), -222)
      general_allocator:delete(wbt1) -- __delete metamethod calls wbt1:destroy()
      --PRINTF!("%s\n", wbt1:treetostring())
      --PRINTF!("gcwip size: %d\n", #forest.gcwip)
      --PRINTF!("240 inserts; sizes... nodes: %d marks %d gcwip: %d\n"
      --          , #forest.nodes, #forest.marks, #forest.gcwip)
      --for k,v in pairs(wbt1) do PRINTF!("k: %d v: %d\n", k, v) end
      --wbt1:destroy()
      --PRINTF!("forest %p <- %p -> %p\n", forest.roots.prev, &forest.roots, forest.roots.next)
      --forest:destroy()--== don't do this if <close> used above!
    end)


    -- A `wbtforest` using gc allocator cannot itself be stack allocated because
    -- it is referenced by wbtmapTs. When a `wbtforest` goes out of scope, the
    -- linked list of wbtrootTs point back at the now non-existant wbtrootT
    -- embedded in the `wbtforest` record. So, `new` must be used to allocate
    -- the `wbtforest`
    nester.it('grow autogc 1', function()
      -- debug
      -- collectgarbage()
      do
        local forest = gc_allocator:new(@wbtforest(integer, integer, nil, GCAllocator))
        local wbt1p = forest:makewbtmap()
        for i = 1, 240 do
          wbt1p = wbt1p:insert(i,-i) -- creates garbage
          -- debug: using this instead of the line above and without the `collectgarbage` above caused a crash... UGH TODO? FIXED?
          --local wbt2p = wbt1p:insert(i,-i)
          --wbt1p = wbt2p -- creates garbage
          --
          expect.equal(#wbt1p, i)
        end
        expect.equal(wbt1p:get(42,-999), -42)
        expect.equal(wbt1p:get(222,-999), -222)
        collectgarbage() -- make sure we go through a gc cycle to test:
        expect.equal(#forest, 1)
        --PRINTF!("forest %p <- %p -> %p\n", forest.roots.prev, &forest.roots, forest.roots.next)
        --PRINTF!("Forest size: %d\n", #forest)
      end
      collectgarbage() -- to trigger collection of forest and wbt1p
    end)

    nester.it('grow autogc 2', function()
      collectgarbage() -- to trigger collection of forest and wbt1p from above
    end)

    -- Here and in revpairs I "cheat" and stack allocate `forest`, but make
    -- sure to `destroy` all `wbtmapT`s
    nester.it('pairs', function()
      local forest: wbtforest(integer, integer) <close>
      local wbt1 = forest:makewbtmap() -- : wbtmapT
      for k,v in pairs(wbt1) do
        expect.equal(k, v) -- to fail since there should be no pairs yet
      end
      for i = 1, 1000 do
        local wbt2 = wbt1:insert(i,-i)
        wbt1, wbt2 = wbt2, wbt1
        wbt2:destroy()
      end
      expect.equal(#wbt1, 1000)
      local i = 1
      for k,v in pairs(wbt1) do
        expect.equal(k, i)
        expect.equal(v, -i)
        i = i + 1
      end
      wbt1:destroy()
    end)

    nester.it('revpairs', function()
      local forest: wbtforest(integer, integer) <close>
      local wbt1 = forest:makewbtmap() -- : wbtmapT
      for k,v in wbt1:revpairs() do
        expect.equal(k, v) -- to fail since there should be no pairs yet
      end
      for i = 1, 1000 do
        local wbt2 = wbt1:insert(i,-i)
        wbt1, wbt2 = wbt2, wbt1
        wbt2:destroy()
      end
      expect.equal(#wbt1, 1000)
      local i = 1000
      for k,v in wbt1:revpairs() do
        expect.equal(k, i)
        expect.equal(v, -i)
        i = i - 1
      end
      wbt1:destroy()
    end)

    nester.it('maintain balance, rank', function()
      local forest: wbtforest(integer, integer) <close>
      local wbt0 = forest:makewbtmap() -- : wbtmapT
      -- empty tree is ordered, balanced, has length zero
      expect.truthy(wbt0:isbalanced())
      expect.truthy(wbt0:isordered(math.mininteger))
      expect.equal(wbt0:countkeys(), #wbt0)
      expect.equal(0, #wbt0)
      -- one entry tree is ordered, balanced, has length one
      local wbt1 = wbt0:insert(1,-1)
      expect.truthy(wbt1:isbalanced())
      expect.truthy(wbt1:isordered(math.mininteger))
      expect.equal(wbt1:countkeys(), #wbt1)
      expect.equal(1, #wbt1)
      -- add 20 items in increasing key order, check ordered, balanced, has length 21
      for k = 2, 21 do
         wbt1 = wbt1:insert(k,-k)
      end
      expect.truthy(wbt1:isbalanced())
      expect.truthy(wbt1:isordered(math.mininteger))
      expect.equal(wbt1:countkeys(), #wbt1)
      expect.equal(21, #wbt1)
      -- add 23 items in decreasing key order, check ordered, balanced, has length 44
      for k = 44, 22, -1 do
         wbt1 = wbt1:insert(k,-k)
      end
      expect.truthy(wbt1:isbalanced())
      expect.truthy(wbt1:isordered(math.mininteger))
      expect.equal(wbt1:countkeys(), #wbt1)
      expect.equal(44, #wbt1)
      -- check that some items are in the length 44 tree
      local ik, iv = wbt1:getmin(-99,99)
      expect.truthy(ik == 1 and iv == -1)
      local xk, xv = wbt1:getmax(-99,99)
      expect.truthy(xk == 44 and xv == -44)
      local av = wbt1:get(25, 500)
      expect.equal(av, -25)
      local nk, nv = wbt1:getNth(6,-99,99) -- nth is 0-based
      expect.truthy(nk == 7 and nv == -7)
      local pk, pv = wbt1:getNth(-7,-99,99) -- nth -1 is last
      expect.truthy(pk == 38 and pv == -38)
      local k0, v0 = wbt0:getmin(-99,99) -- note: empty tree
      expect.truthy(k0 == -99 and v0 == 99)
      local k1, v1 = wbt0:getmax(-99,99) -- note: empty tree
      expect.truthy(k1 == -99 and v1 == 99)
      expect.truthy(wbt1:isbalanced())
      expect.truthy(wbt1:isordered(math.mininteger))
      expect.equal(wbt1:countkeys(), #wbt1)
      expect.equal(44, #wbt1)
      local ek, ev = wbt1:getNth(98,-99,99) -- off the end, right
      expect.truthy(ek == -99 and ev == 99)
      local bk, bv = wbt1:getNth(-77,-88,88) -- off the end, left
      expect.truthy(bk == -88 and bv == 88)
      expect.truthy(wbt1:isbalanced())
      expect.truthy(wbt1:isordered(math.mininteger))
      expect.equal(wbt1:countkeys(), #wbt1)
      expect.equal(44, #wbt1)
      expect.truthy(wbt0:isbalanced())
      expect.truthy(wbt0:isordered(math.mininteger))
      expect.equal(wbt0:countkeys(), #wbt0)
      expect.equal(0, #wbt0)
    end)

    nester.it('next, prev, & rank', function()
      local forest: wbtforest(integer, integer) <close>
      local wbt1 = forest:makewbtmap() -- : wbtmapT
      for k = 1, 44 do
         wbt1 = wbt1:insert(k,-k)
      end
      local k1,v1 = wbt1:getnext(3,-99,99)
      expect.truthy(k1 == 4 and v1 == -4)
      local k2,v2 = wbt1:getprev(22,-99,99)
      expect.truthy(k2 == 21 and v2 == -21)
      local k3,v3 = wbt1:getprev(1,-99,99)
      expect.truthy(k3 == -99 and v3 == 99)
      local k4,v4 = wbt1:getnext(math.mininteger,-99,99)
      expect.truthy(k4 == 1 and v4 == -1)
      local k5,v5 = wbt1:getprev(100,-99,99)
      expect.truthy(k5 == 44 and v5 == -44)
      expect.truthy(wbt1:isbalanced())
      expect.truthy(wbt1:isordered(math.mininteger))
      expect.equal(wbt1:countkeys(), #wbt1)
      expect.equal(44, #wbt1)
      expect.truthy(wbt1:getrank(1,-99) == 0)
      for i = 2, 44 do
        expect.truthy(wbt1:getrank(i,-99) == i-1)
      end
      -- for code coverage...
      for i = 2, 45 do
        local k,v = wbt1:getprev(i,-99,99)
        expect.truthy(k == i-1 and v == -(i-1))
      end
      for i = 0, 43 do
        local k,v = wbt1:getnext(i,-99,99)
        expect.truthy(k == i+1 and v == -(i+1))
      end
    end)

    nester.it('delete variations', function()
      local forest: wbtforest(integer, integer) <close>
      local wbt1 = forest:makewbtmap() -- : wbtmapT
      for k = 1, 44 do
         wbt1 = wbt1:insert(k,-k)
      end
      wbt1 = wbt1:delete(13)
      expect.truthy(wbt1:isbalanced())
      expect.truthy(wbt1:isordered(math.mininteger))
      expect.equal(43, #wbt1)
      local res = wbt1:get(13, -999)
      expect.equal(res, -999)
      res = wbt1:get(26, -999)
      expect.equal(res, -26)
      wbt1 = wbt1:delete(26)
      expect.truthy(wbt1:isbalanced())
      expect.truthy(wbt1:isordered(math.mininteger))
      expect.equal(42, #wbt1)
      res = wbt1:get(26, -999)
      expect.equal(res, -999)
      res = wbt1:get(1, -999)
      expect.equal(res, -1)
      wbt1 = wbt1:delmin()
      expect.truthy(wbt1:isbalanced())
      expect.truthy(wbt1:isordered(math.mininteger))
      expect.equal(41, #wbt1)
      res = wbt1:get(1, -999)
      expect.equal(res, -999)
      res = wbt1:get(44, -999)
      expect.equal(res, -44)
      wbt1 = wbt1:delmax()
      expect.truthy(wbt1:isbalanced())
      expect.truthy(wbt1:isordered(math.mininteger))
      expect.equal(40, #wbt1)
      res = wbt1:get(44, -999)
      expect.equal(res, -999)
      --
      local wbt0 = forest:makewbtmap()
      wbt0 = wbt0:delmin()
      wbt0 = wbt0:delmin()
      wbt0 = wbt0:delete(13)
      expect.truthy(wbt0:isbalanced())
      expect.truthy(wbt0:isordered(math.mininteger))
      expect.equal( 0, #wbt0)
      expect.equal(40, #wbt1)
    end)

    nester.it('delete random', function()
      local forest: wbtforest(integer, integer) <close>
      local wbt1 = forest:makewbtmap() -- : wbtmapT
      local n: integer = 1000
      for k = 1, n do
         wbt1 = wbt1:insert(k,-k)
      end
      math.randomseed(42,356)
      while n > 0 do
        local i = math.random(n)
        local k0,v0 = wbt1:getNth(i-1, -99, 99)
        expect.truthy(k0 ~= -99)
        wbt1 = wbt1:delete(k0)
        local v1 = wbt1:get(k0,99)
        expect.equal(v1, 99)
        n = n - 1
        expect.truthy(wbt1:isbalanced())
        expect.truthy(wbt1:isordered(math.mininteger))
        if n ~= #wbt1 then
          PRINTF!("%d: %s\n", n, wbt1:treetostring())
        end
        expect.equal(n, #wbt1)
      end
    end)

    nester.it('insert to replace values', function()
      local forest: wbtforest(integer, integer) <close>
      local wbt1 = forest:makewbtmap() -- : wbtmapT
      for k = 1, 9 do
         wbt1 = wbt1:insert(k,-k)
      end
      expect.truthy(wbt1:isbalanced())
      expect.truthy(wbt1:isordered(math.mininteger))
      expect.equal(9, #wbt1)
      expect.equal(wbt1:get(3,99), -3)
      wbt1 = wbt1:insert(3, -33)
      expect.equal(9, #wbt1)
      expect.truthy(wbt1:isbalanced())
      expect.truthy(wbt1:isordered(math.mininteger))
      expect.equal(wbt1:get(3,99), -33)
    end)

  end)
end)

nester.report() -- Print overall statistic of the tests run.
nester.exit() -- Exit with success if all tests passed.
